mv /etc/osp/samples/osgp-adapter-ws-core.properties.sample /etc/osp/osgp-adapter-ws-core.properties       
mv /etc/osp/samples/osgp-adapter-ws-publiclighting.properties.sample /etc/osp/osgp-adapter-ws-publiclighting.properties       
mv /etc/osp/samples/osgp-adapter-ws-shared-db.properties.sample /etc/osp/osgp-adapter-ws-shared-db.properties       
mv /etc/osp/samples/osgp-core.properties.sample /etc/osp/osgp-core.properties                
mv /etc/osp/samples/web-device-simulator.properties.sample /etc/osp/web-device-simulator.properties       
mv /etc/osp/samples/osgp-logging.properties.sample /etc/osp/osgp-logging.properties
mv /etc/osp/samples/osgp-domain-logging.properties.sample /etc/osp/osgp-domain-logging.properties
mv /etc/osp/samples/osgp-adapter-domain-admin.properties.sample /etc/osp/osgp-adapter-domain-admin.properties       
mv /etc/osp/samples/osgp-adapter-domain-core.properties.sample /etc/osp/osgp-adapter-domain-core.properties       
mv /etc/osp/samples/osgp-adapter-domain-publiclighting.properties.sample /etc/osp/osgp-adapter-domain-publiclighting.properties 
mv /etc/osp/samples/osgp-adapter-ws-admin.properties.sample /etc/osp/osgp-adapter-ws-admin.properties
mv /etc/osp/samples/jasper-interface.properties.sample /etc/osp/jasper-interface.properties
mv /etc/osp/samples/osgp-adapter-domain-admin-logback.xml.sample /etc/osp/osgp-adapter-domain-admin-logback.xml
mv /etc/osp/samples/osgp-adapter-domain-core-logback.xml.sample /etc/osp/osgp-adapter-domain-core-logback.xml
mv /etc/osp/samples/osgp-adapter-domain-distributionautomation-logback.xml.sample /etc/osp/osgp-adapter-domain-distributionautomation-logback.xml
mv /etc/osp/samples/osgp-adapter-domain-distributionautomation.properties.sample /etc/osp/osgp-adapter-domain-distributionautomation.properties
mv /etc/osp/samples/osgp-adapter-domain-microgrids-logback.xml.sample /etc/osp/osgp-adapter-domain-microgrids-logback.xml
mv /etc/osp/samples/osgp-adapter-domain-microgrids.properties.sample /etc/osp/osgp-adapter-domain-microgrids.properties
mv /etc/osp/samples/osgp-adapter-domain-publiclighting-logback.xml.sample /etc/osp/osgp-adapter-domain-publiclighting-logback.xml
mv /etc/osp/samples/osgp-adapter-domain-smartmetering-logback.xml.sample /etc/osp/osgp-adapter-domain-smartmetering-logback.xml
mv /etc/osp/samples/osgp-adapter-domain-smartmetering.properties.sample /etc/osp/osgp-adapter-domain-smartmetering.properties
mv /etc/osp/samples/osgp-adapter-domain-tariffswitching-logback.xml.sample /etc/osp/osgp-adapter-domain-tariffswitching-logback.xml
mv /etc/osp/samples/osgp-adapter-domain-tariffswitching.properties.sample /etc/osp/osgp-adapter-domain-tariffswitching.properties
mv /etc/osp/samples/osgp-adapter-protocol-dlms-logback.xml.sample /etc/osp/osgp-adapter-protocol-dlms-logback.xml
mv /etc/osp/samples/osgp-adapter-protocol-dlms.properties.sample /etc/osp/osgp-adapter-protocol-dlms.properties
mv /etc/osp/samples/osgp-adapter-protocol-iec61850-logback.xml.sample /etc/osp/osgp-adapter-protocol-iec61850.properties
mv /etc/osp/samples/osgp-adapter-protocol-oslp-elster-logback.xml.sample /etc/osp/osgp-adapter-protocol-oslp-elster-logback.xml
mv /etc/osp/samples/osgp-adapter-protocol-oslp-elster.properties.sample /etc/osp/osgp-adapter-protocol-oslp-elster.properties
mv /etc/osp/samples/osgp-adapter-ws-admin-logback.xml.sample /etc/osp/osgp-adapter-ws-admin-logback.xml
mv /etc/osp/samples/osgp-adapter-ws-core-logback.xml.sample /etc/osp/osgp-adapter-ws-core-logback.xml
mv /etc/osp/samples/osgp-adapter-ws-distributionautomation-logback.xml.sample /etc/osp/osgp-adapter-ws-distributionautomation-logback.xml
mv /etc/osp/samples/osgp-adapter-ws-distributionautomation.properties.sample /etc/osp/osgp-adapter-ws-distributionautomation.properties
mv /etc/osp/samples/osgp-adapter-ws-microgrids-logback.xml.sample /etc/osp/osgp-adapter-ws-microgrids-logback.xml
mv /etc/osp/samples/osgp-adapter-ws-microgrids.properties.sample /etc/osp/osgp-adapter-ws-microgrids.properties
mv /etc/osp/samples/osgp-adapter-ws-publiclighting-logback.xml.sample /etc/osp/osgp-adapter-ws-publiclighting-logback.xml
mv /etc/osp/samples/osgp-adapter-ws-smartmetering-logback.xml.sample /etc/osp/osgp-adapter-ws-smartmetering-logback.xml
mv /etc/osp/samples/osgp-adapter-ws-smartmetering.properties.sample /etc/osp/osgp-adapter-ws-smartmetering.properties
mv /etc/osp/samples/osgp-adapter-ws-tariffswitching-logback.xml.sample /etc/osp/osgp-adapter-ws-tariffswitching-logback.xml
mv /etc/osp/samples/osgp-adapter-ws-tariffswitching.properties.sample /etc/osp/osgp-adapter-ws-tariffswitching.properties
mv /etc/osp/samples/osgp-core-db-api-iec61850.properties.sample /etc/osp/osgp-core-db-api-iec61850.properties
mv /etc/osp/samples/osgp-core-db-api.properties.sample /etc/osp/osgp-core-db-api.properties
mv /etc/osp/samples/osgp-core-logback.xml.sample /etc/osp/osgp-core-logback.xml
mv /etc/osp/samples/osgp-logging-logback.xml.sample /etc/osp/osgp-logging-logback.xml
mv /etc/osp/samples/signing-server-logback.xml.sample /etc/osp/signing-server-logback.xml
mv /etc/osp/samples/signing-server.properties.sample /etc/osp/signing-server.properties
mv /etc/osp/samples/web-device-simulator-logback.xml.sample /etc/osp/web-device-simulator-logback.xml
mv /etc/osp/samples/osgp-adapter-protocol-iec61850.properties.sample /etc/osp/osgp-adapter-protocol-iec61850.properties
