mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/platform/osgp-adapter-domain-admin/target/osgp-adapter-domain-admin-$VERSION.war /home/dev/Tools/tomcat8/tmp/osgp-adapter-domain-admin.war
mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/platform/osgp-adapter-domain-core/target/osgp-adapter-domain-core-$VERSION.war /home/dev/Tools/tomcat8/tmp/osgp-adapter-domain-core.war
mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/platform/osgp-adapter-domain-publiclighting/target/osgp-adapter-domain-publiclighting-$VERSION.war /home/dev/Tools/tomcat8/tmp/osgp-adapter-domain-publiclighting.war
mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/platform/osgp-adapter-domain-shared/target/osgp-adapter-domain-shared-$VERSION.jar /home/dev/Tools/tomcat8/tmp/osgp-adapter-domain-shared.jar
mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/platform/osgp-adapter-ws-admin/target/osgp-adapter-ws-admin-$VERSION.war /home/dev/Tools/tomcat8/tmp/osgp-adapter-ws-admin.war
mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/platform/osgp-adapter-ws-core/target/osgp-adapter-ws-core-$VERSION.war /home/dev/Tools/tomcat8/tmp/osgp-adapter-ws-core.war
mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/platform/osgp-adapter-ws-publiclighting/target/osgp-adapter-ws-publiclighting-$VERSION.war /home/dev/Tools/tomcat8/tmp/osgp-adapter-ws-publiclighting.war
mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/platform/osgp-adapter-ws-shared/target/osgp-adapter-ws-shared-$VERSION.jar /home/dev/Tools/tomcat8/tmp/osgp-adapter-ws-shared.jar
mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/platform/osgp-adapter-ws-shared-db/target/osgp-adapter-ws-shared-db-$VERSION.jar /home/dev/Tools/tomcat8/tmp/osgp-adapter-ws-shared-db.jar
mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/platform/osgp-core/target/osgp-core-$VERSION.war /home/dev/Tools/tomcat8/tmp/osgp-core.war
mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/protocol-adapter-oslp/osgp-core-db-api/target/osgp-core-db-api-$VERSION.jar /home/dev/Tools/tomcat8/tmp/osgp-core-db-api.jar
mv  /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/protocol-adapter-oslp/osgp-adapter-protocol-oslp-elster/target/osgp-protocol-adapter-oslp-elster-$VERSION.war /home/dev/Tools/tomcat8/tmp/osgp-adapter-protocol-oslp-elster.war
mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/protocol-adapter-oslp/oslp/target/oslp-$VERSION.jar /home/dev/Tools/tomcat8/tmp/oslp.jar
mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/protocol-adapter-oslp/signing-server/target/signing-server-$VERSION.war /home/dev/Tools/tomcat8/tmp/signing-server.war
mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/platform/osgp-domain-core/target/osgp-domain-core-$VERSION.jar /home/dev/Tools/tomcat8/tmp/osgp-domain-core.jar
mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/platform/osgp-domain-logging/target/osgp-domain-logging-$VERSION.jar /home/dev/Tools/tomcat8/tmp/osgp-domain-logging.jar
mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/platform/osgp-logging/target/osgp-logging-$VERSION.war /home/dev/Tools/tomcat8/tmp/osgp-logging.war
mv /home/dev/Sources/OSGP/open-smart-grid-platform/osgp/platform/osgp-throttling-service/target/osgp-throttling-service-$VERSION.war /home/dev/Tools/tomcat8/tmp/osgp-throttling-service.war
