version: "3.7"

services: 
  tdengine:
    image: zitsen/tdengine-server:2.1.2.0
    environment: 
      TAOS_FQDN: "tdengine"
  grafana:
    image: grafana/grafana:6.2.4
    volumes:
      - ./dist:/var/lib/grafana/plugins/tdengine
    ports:
      - 3001:3000